apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      name: node
      labels:
        app: node
    spec:
      containers:
      - image: k8schandra/nodeapp:v1
        name: nodejs
        resources:
          requests:
            cpu: 100m
