apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
spec:
  containers:
  - image: busybox
    name: test-pod
    command: ["sleep", "10000"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: Username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: Password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
