apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa-test
spec:
  serviceAccount: test
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: k8schandra/kubectl-proxy
