apiVersion: v1
kind: Pod
metadata:
  name: memoryhog
spec:
  containers:
  - image: docker.io/luksa/memoryhog
    args: ["15000000000"]
    name: main
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 500m
        memory: 100Mi
