apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-every-fifteen-minutes
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: k8schandra/batchjob
