apiVersion: v1
kind: Pod
metadata:
  name: node-gpu
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu
            operator: In
            values:
            - "true"
  containers:
  - image: k8schandra/nodeapp:v1
    name: node
